Controllers films users
catarena-s/java-filmorate pull request #1
Opened 2023-01-24 15:53 UTC by catarena-s

2023-01-25 19:59 UTC, z8q requested changes
Привет, Екатерина!

Комменты оставил.
Правки незначительные, но в контроллере я бы вывел все методы для удобства.
В остальном все ок. Круто, что еще свои аннотации сделала.

2023-01-25 19:59 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +public class FilmController extends Controller<Film> {
Будет лучше обозначить все методы в контроллере, чтобы все действия были на виду. Даже если в самих методах будет незначительное действие, логирование например, а остальное в super() уходить, это все равно будет легче воспринимать.

2023-01-25 19:59 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/Service.java
> +            map.put(obj.getId(), obj);
Если будем обновлять user, перед добавлением валидация будет нужна.

2023-01-25 21:34 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +public class FilmController extends Controller<Film> {
Добавила в контроллеры метода, перенесла в в них логирование.

2023-01-25 21:34 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/service/Service.java
> +            map.put(obj.getId(), obj);
Поправила.

2023-01-25 21:34 UTC, catarena-s commented
Привет!
Твои замечания поправила:
1. Обозначила все методы в контроллерах, чтобы все действия были на виду(FilmController, UserController).
2. Логирование перенесено из Service в методы контроллеров.
3. В метод update добавлена валидация.

Дополнительно, по рекомендации наставника:
4. Убрать аннотацию @Data из классов модели(File, User). Вместо неё:  @Getter, @Setter, @EqualsAndHashCode.

2023-01-26 19:37 UTC, z8q approved these changes
Привет, Екатерина!

Доработки сделаны, все хорошо, работу принимаю :)

2023-01-26 20:32 UTC, merged