feat: спринт 10
catarena-s/java-filmorate pull request #2
Opened 2023-02-05 17:27 UTC by catarena-s

1. Переработать архитектуру:
- хранение данных о фильмах и пользователях в отдельных классах пакета storage
- логика приложения в пакете service(UserService и FilmService)
2. Переделать код в контроллерах, сервисах и хранилищах под внедрение зависимостей.
3. Доработать контроллеры: получение дополнительной информации о пользователе и о фильме.

2023-02-06 16:04 UTC, z8q requested changes
Привет!
Оставил несколько комментариев.

2023-02-06 16:04 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/Storage.java
> +    T get(long id);
Лучше назвать getById

2023-02-06 16:04 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/AbstractStorage.java
> +public abstract class AbstractStorage<T extends FilmorateObject> {
Не очень нравится, что интерфейс реализуют InMemoryStorage классы, а по сути override происходит здесь.
Может быть будет лучше, чтобы абстракт имплементировал интерфейс и переопределял методы явно, с аннотацией `@Override`

2023-02-06 16:04 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService service) {
Тут и в  UserController без `@Autowired`?
https://www.baeldung.com/spring-autowired-abstract-class

2023-02-06 16:04 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmorateException.java
>          super(message);
`log.error(message);` не уверен, хорошее ли решение. Может быть будут какие-то ошибки, которые мы не захотим логировать. Или захотим поставить только `warn`

2023-02-07 17:10 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/storage/Storage.java
> +    T get(long id);
Переименовала.

2023-02-07 17:10 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/storage/AbstractStorage.java
> +public abstract class AbstractStorage<T extends FilmorateObject> {
Добавила имплементацию интерфейса в абстрактный класс, методы пометила аннотацией.

2023-02-07 17:10 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService service) {
Спасибо, за ссылку. Аннотацию поставила.
В теории было написано, что если конструктор один, то аннотация не нужна - спринг и так всё поймет. Наставник тоже обычно его не проставляет. Вот и в результате удалила.

2023-02-07 17:10 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmorateException.java
>          super(message);
Возможность бросить ошибку без логирования добавила. Для варианта с логированием сделала возможность выбрать уровень важности.

2023-02-07 17:10 UTC, catarena-s commented
Привет, Кирилл!
Замечания проработала.
Дополнительно: перенесла метод валидации из сторедж в сервис(как-то упустила этот момент ТЗ).

2023-02-07 19:22 UTC, z8q approved these changes
Привет!
Работу принимаю

2023-02-07 19:34 UTC, merged