Add database - спринт 11
catarena-s/java-filmorate pull request #3
Opened 2023-03-01 17:17 UTC by catarena-s

1)схема и описание БД добавлены в README.md
2)добавлены DAO-классы: FilmDbStorage, UserDBStorage, RatingMPADbStorage, GenreDbStorage, LikeDbStorage, FriendshipDbStorage.
3)для Genre добавлены GenreController и GenreService, для RatingMPA - RatingMPAController и RatingMPAService.
4)написаны интеграционные тесты для DAO-объектов.

2023-03-02 20:35 UTC, z8q requested changes
Привет!
Комментарии оставил

2023-03-02 20:35 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    protected GenreController(GenreService service) {
Можно ли тут сделать инджект в поле service как в классе RatingMPAController?

2023-03-02 20:35 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Genre> genres = new TreeSet<>(Comparator.comparing(Genre::getId));
Если id жанрах в отправляемом объекте не укажем, приходит довольно подробная ошибка:
{
`"error": "PreparedStatementCallback; SQL [INSERT INTO film_genre(film_id, genre_id) VALUES(? , ? ) ]; Referential integrity constraint violation: \"CONSTRAINT_7: PUBLIC.FILM_GENRE FOREIGN KEY(GENRE_ID) REFERENCES PUBLIC.GENRE(GENRE_ID) (0)\"; SQL statement:\nINSERT INTO film_genre(film_id, genre_id) VALUES(? , ? ) [23506-214]; nested exception is org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referential integrity constraint violation: \"CONSTRAINT_7: PUBLIC.FILM_GENRE FOREIGN KEY(GENRE_ID) REFERENCES PUBLIC.GENRE(GENRE_ID) (0)\"; SQL statement:\nINSERT INTO film_genre(film_id, genre_id) VALUES(? , ? ) [23506-214]",
"description": null`
}
В лог для внутреннего пользования записать норм, но возвращать лучше что-то общее. Это больше на будущее, сейчас не критично

2023-03-02 20:35 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public void addFriend(Long fiendId) {
Когда добавляем жанр в set фильма, в аргументах используем объект. 
Тут тоже можно было бы принимать сразу экземпляр типа Friend

2023-03-02 20:35 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    protected Film makeFilm(ResultSet rs) throws SQLException {
Тут одновременно и builder используем, и сеттеры.
Еще дополнительные запросы в базу.
Например для формирования топ-списка фильмов на каждый фильм приходится еще по 4 запроса:
[SELECT * FROM rating WHERE rating_id = ? ORDER BY rating_id]
[SELECT genre_id FROM film_genre WHERE film_id = ? ORDER BY genre_id]
[SELECT * FROM genre WHERE genre_id = ? ORDER BY genre_id]
[SELECT user_id FROM likes WHERE film_id = ?]

2023-03-02 20:35 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/GenreDbStorage.java
> +                .map(this::getById)
Тоже дополнительно на каждый id еще по запросу идет

2023-03-08 07:55 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    protected GenreController(GenreService service) {
Да, можно. Почему-то пропустила этот класс.

2023-03-08 07:56 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Genre> genres = new TreeSet<>(Comparator.comparing(Genre::getId));
Эту ситуацию воспроизвести не получилось, но места где могли выводиться настолько подробные сообщения вроде бы поправила.

2023-03-08 07:56 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public void addFriend(Long fiendId) {
Поправила

2023-03-08 07:56 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    protected Film makeFilm(ResultSet rs) throws SQLException {
Оставила builder.
Количество запросов к базе вроде бы уменьшила, но мне кажется что-то я намудрила. Есть ощущение, что можно проще, но проще не придумалось.

2023-03-08 07:56 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/GenreDbStorage.java
> +                .map(this::getById)
Поправила

2023-03-08 07:56 UTC, catarena-s commented
Привет. 
Замечания поправила.
Количество запросов в БД сократила, кажется.

Дополнительно:
1) по рекомендация наставника: удалила классы InMemoryFilmStorage, InMemoryStorage, InMemoryUserStorage
2) тесты для разных стореджей вынесла в отдельные классы, а то как-то много их вышло

2023-03-08 10:56 UTC, z8q approved these changes

2023-03-08 10:56 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Genre> genres = new TreeSet<>(Comparator.comparing(Genre::getId));
Поправить получилось, теперь приходит ответ такого вида:
`{
"error": "Ошибка добавления",
"description": "При добавлении фильма произошла ошибка: {Film(super=FilmorateObject(id=0), name=Die Hard, duration=1234567, description=Action movie with Br-s Wil-s, releaseDate=1988-07-22, genres=[Genre(super=FilmorateObject(id=0), name=drama)], mpa=RatingMPA(super=FilmorateObject(id=5), name=NC-17), likes=[])}"
}`


Чтобы воспроизвести, достаточно отправить на хендлер `http://localhost:8080/films/` POST-запрос с таким json:
{
	"name": "Die Hard",
	"description": "Action movie with Br-s Wil-s",
	"releaseDate": "1988-07-22",
	"duration": 1234567,
	"rating": 100,
	"mpa": {
		"id": 5,
		"name":"NC-17",
		"description": "17+"
	},
	"genres": [ `тут не указываем id для объектов, и ошибка воспроизводится`
		{
			"name": "action"
		},
		{
			"name": "drama"
		},
		{
			"name": "comedy"
		}
	]
}

2023-03-08 11:27 UTC, merged